import csv
import io
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st

plt.style.use("seaborn-v0_8-whitegrid")
st.set_page_config(layout="wide")
st.title("🌲 Novak's TriNetX Forest Plot Generator")

required_cols = [
    "Outcome",
    "Risk, Odds, or Hazard Ratio",
    "Effect Size (Cohen's d, approx.)",
    "Lower CI",
    "Upper CI",
]


def compute_cohens_d(rr):
    try:
        if pd.isnull(rr):
            return np.nan
        val = float(rr)
        if val <= 0:
            return np.nan
        return np.log(val) * (np.sqrt(3) / np.pi)
    except Exception:
        return np.nan


def clean_cell(value):
    if value is None:
        return ""
    text = str(value).replace("\ufeff", "").strip()
    text = text.strip('"').strip()
    return text


def parse_float(value):
    text = clean_cell(value).replace(",", "")
    if text in {"", " ", "nan", "None"}:
        return None
    try:
        return float(text)
    except Exception:
        return None


def next_nonblank_row(rows, start_idx):
    for idx in range(start_idx, len(rows)):
        if any(clean_cell(cell) for cell in rows[idx]):
            return idx
    return None


def extract_section_triplet(rows, section_name):
    for i, row in enumerate(rows):
        first = clean_cell(next((cell for cell in row if clean_cell(cell)), ""))
        if first == section_name:
            header_idx = next_nonblank_row(rows, i + 1)
            data_idx = next_nonblank_row(rows, (header_idx + 1) if header_idx is not None else i + 1)
            if data_idx is None:
                return None
            numeric_values = [parse_float(cell) for cell in rows[data_idx]]
            numeric_values = [x for x in numeric_values if x is not None]
            if len(numeric_values) >= 3:
                return {
                    "estimate": numeric_values[0],
                    "lower": numeric_values[1],
                    "upper": numeric_values[2],
                }
    return None


def extract_title_from_rows(rows):
    for row in rows[:8]:
        first = clean_cell(next((cell for cell in row if clean_cell(cell)), ""))
        if first and first != "Generated by TriNetX":
            return first
    return ""


def clean_title(title):
    title = clean_cell(title)
    title = re.sub(r"\s*Measures of Association Table\s*$", "", title, flags=re.IGNORECASE)
    title = re.sub(r"\s+", " ", title).strip(" -_")
    return title


def clean_filename(name):
    stem = Path(name).stem
    stem = re.sub(r"(?i)_result_[a-z0-9]+_moa_table$", "", stem)
    stem = re.sub(r"(?i)_moa_table$", "", stem)
    stem = re.sub(r"(?i)_table$", "", stem)
    stem = stem.replace("_", " ").replace("-", " ")
    stem = re.sub(r"\s+", " ", stem).strip()
    return stem


def looks_generic(label):
    text = (label or "").strip().lower()
    return bool(re.match(r"^outcome\s*\d+(\s+result.*)?$", text))


def choose_outcome_label(title, filename):
    cleaned_title = clean_title(title)
    cleaned_filename = clean_filename(filename)
    if cleaned_title and not looks_generic(cleaned_title):
        return cleaned_title
    if cleaned_filename:
        return cleaned_filename
    return cleaned_title or "Outcome"


def parse_trinetx_csv_text(file_bytes):
    text = file_bytes.decode("utf-8-sig", errors="ignore")
    rows = list(csv.reader(io.StringIO(text)))
    return rows, text


def parse_trinetx_excel_rows(file_bytes):
    raw = pd.read_excel(io.BytesIO(file_bytes), header=None, dtype=str)
    rows = raw.fillna("").values.tolist()
    joined = "\n".join([",".join([clean_cell(cell) for cell in row]) for row in rows])
    return rows, joined


def parse_trinetx_moa_rows(rows, filename):
    title = extract_title_from_rows(rows)
    risk_ratio = extract_section_triplet(rows, "Risk Ratio")
    odds_ratio = extract_section_triplet(rows, "Odds Ratio")
    hazard_ratio = extract_section_triplet(rows, "Hazard Ratio")

    if not any([risk_ratio, odds_ratio, hazard_ratio]):
        return None

    return {
        "Outcome": choose_outcome_label(title, filename),
        "Source File": filename,
        "Risk Ratio": risk_ratio["estimate"] if risk_ratio else np.nan,
        "RR Lower CI": risk_ratio["lower"] if risk_ratio else np.nan,
        "RR Upper CI": risk_ratio["upper"] if risk_ratio else np.nan,
        "Odds Ratio": odds_ratio["estimate"] if odds_ratio else np.nan,
        "OR Lower CI": odds_ratio["lower"] if odds_ratio else np.nan,
        "OR Upper CI": odds_ratio["upper"] if odds_ratio else np.nan,
        "Hazard Ratio": hazard_ratio["estimate"] if hazard_ratio else np.nan,
        "HR Lower CI": hazard_ratio["lower"] if hazard_ratio else np.nan,
        "HR Upper CI": hazard_ratio["upper"] if hazard_ratio else np.nan,
    }


def standardize_existing_forest_table(df):
    working = df.copy()
    for col in required_cols:
        if col not in working.columns:
            working[col] = np.nan

    numeric_cols = [
        "Risk, Odds, or Hazard Ratio",
        "Lower CI",
        "Upper CI",
        "Effect Size (Cohen's d, approx.)",
    ]
    for col in numeric_cols:
        working[col] = pd.to_numeric(working[col], errors="coerce")

    if working["Effect Size (Cohen's d, approx.)"].isna().all():
        working["Effect Size (Cohen's d, approx.)"] = working["Risk, Odds, or Hazard Ratio"].apply(compute_cohens_d)

    return working[required_cols]


def detect_and_load_uploaded_files(uploaded_files):
    parsed_trinetx_rows = []
    parsed_standard_tables = []
    parsing_notes = []

    for uploaded_file in uploaded_files:
        file_bytes = uploaded_file.getvalue()
        filename = uploaded_file.name
        suffix = Path(filename).suffix.lower()

        try:
            if suffix == ".csv":
                rows, raw_text = parse_trinetx_csv_text(file_bytes)
                if "Generated by TriNetX" in raw_text and any(x in raw_text for x in ["Risk Ratio", "Odds Ratio", "Hazard Ratio"]):
                    parsed = parse_trinetx_moa_rows(rows, filename)
                    if parsed is not None:
                        parsed_trinetx_rows.append(parsed)
                        continue
                standard_df = pd.read_csv(io.BytesIO(file_bytes))
                parsed_standard_tables.append(standardize_existing_forest_table(standard_df))
            elif suffix in {".xlsx", ".xls"}:
                try:
                    rows, raw_text = parse_trinetx_excel_rows(file_bytes)
                    if "Generated by TriNetX" in raw_text and any(x in raw_text for x in ["Risk Ratio", "Odds Ratio", "Hazard Ratio"]):
                        parsed = parse_trinetx_moa_rows(rows, filename)
                        if parsed is not None:
                            parsed_trinetx_rows.append(parsed)
                            continue
                except Exception:
                    pass
                standard_df = pd.read_excel(io.BytesIO(file_bytes))
                parsed_standard_tables.append(standardize_existing_forest_table(standard_df))
            else:
                parsing_notes.append(f"Skipped unsupported file type: {filename}")
        except Exception as e:
            parsing_notes.append(f"Could not parse {filename}: {e}")

    return parsed_trinetx_rows, parsed_standard_tables, parsing_notes


def build_plot_table_from_trinetx(parsed_rows, preferred_measure):
    out_rows = []

    for row in parsed_rows:
        measure_priority = [preferred_measure]
        for candidate in ["Risk Ratio", "Odds Ratio", "Hazard Ratio"]:
            if candidate not in measure_priority:
                measure_priority.append(candidate)

        chosen_measure = None
        estimate = lower = upper = np.nan

        for candidate in measure_priority:
            if candidate == "Risk Ratio" and pd.notnull(row.get("Risk Ratio", np.nan)):
                chosen_measure = candidate
                estimate = row["Risk Ratio"]
                lower = row["RR Lower CI"]
                upper = row["RR Upper CI"]
                break
            if candidate == "Odds Ratio" and pd.notnull(row.get("Odds Ratio", np.nan)):
                chosen_measure = candidate
                estimate = row["Odds Ratio"]
                lower = row["OR Lower CI"]
                upper = row["OR Upper CI"]
                break
            if candidate == "Hazard Ratio" and pd.notnull(row.get("Hazard Ratio", np.nan)):
                chosen_measure = candidate
                estimate = row["Hazard Ratio"]
                lower = row["HR Lower CI"]
                upper = row["HR Upper CI"]
                break

        out_rows.append({
            "Outcome": row["Outcome"],
            "Risk, Odds, or Hazard Ratio": estimate,
            "Effect Size (Cohen's d, approx.)": compute_cohens_d(estimate),
            "Lower CI": lower,
            "Upper CI": upper,
            "Effect Type": chosen_measure,
            "Source File": row["Source File"],
        })

    return pd.DataFrame(out_rows)


input_mode = st.radio(
    "Select data input method:", ["📤 Upload file(s)", "✍️ Manual entry"], index=0, horizontal=True
)

df = None

if input_mode == "📤 Upload file(s)":
    uploaded_files = st.file_uploader(
        "Upload one normalized forest-plot table or multiple raw TriNetX outcome tables",
        type=["csv", "xlsx", "xls"],
        accept_multiple_files=True,
    )

    if uploaded_files:
        preferred_measure = st.sidebar.selectbox(
            "Preferred TriNetX estimate to plot",
            ["Risk Ratio", "Odds Ratio", "Hazard Ratio"],
            index=0,
            help="If a raw TriNetX file contains multiple estimates, the app will use this measure when available.",
        )

        parsed_trinetx_rows, parsed_standard_tables, parsing_notes = detect_and_load_uploaded_files(uploaded_files)

        assembled_tables = []
        if parsed_trinetx_rows:
            trinetx_df = build_plot_table_from_trinetx(parsed_trinetx_rows, preferred_measure)
            assembled_tables.append(trinetx_df[required_cols + ["Effect Type", "Source File"]])
        if parsed_standard_tables:
            for table in parsed_standard_tables:
                table = table.copy()
                table["Effect Type"] = np.nan
                table["Source File"] = np.nan
                assembled_tables.append(table[required_cols + ["Effect Type", "Source File"]])

        if assembled_tables:
            combined_df = pd.concat(assembled_tables, ignore_index=True)
            st.subheader("Parsed data preview")
            st.caption("You can edit outcome labels, reorder rows, or insert section headers using ## before a label.")
            editable_cols = required_cols + ["Effect Type", "Source File"]
            edited_df = st.data_editor(
                combined_df[editable_cols],
                num_rows="dynamic",
                use_container_width=True,
                key="uploaded_table_editor",
                column_config={
                    "Effect Size (Cohen's d, approx.)": st.column_config.NumberColumn(
                        "Effect Size (Cohen's d, approx.)",
                        disabled=True,
                        help="Auto-calculated as ln(RR/OR/HR) × sqrt(3)/π",
                    ),
                    "Effect Type": st.column_config.TextColumn(disabled=True),
                    "Source File": st.column_config.TextColumn(disabled=True),
                },
            )
            edited_df["Effect Size (Cohen's d, approx.)"] = edited_df["Risk, Odds, or Hazard Ratio"].apply(compute_cohens_d)
            df = edited_df
        else:
            st.error("No usable forest-plot data could be parsed from the uploaded files.")

        if parsing_notes:
            with st.expander("Parsing notes"):
                for note in parsing_notes:
                    st.write(f"- {note}")
else:
    default_data = pd.DataFrame({
        "Outcome": ["## Cardiovascular", "Hypertension", "Stroke", "## Metabolic", "Diabetes", "Obesity"],
        "Risk, Odds, or Hazard Ratio": [None, 1.5, 1.2, None, 0.85, 1.2],
        "Lower CI": [None, 1.2, 1.0, None, 0.7, 1.0],
        "Upper CI": [None, 1.8, 1.5, None, 1.0, 1.4],
    })
    default_data["Effect Size (Cohen's d, approx.)"] = default_data["Risk, Odds, or Hazard Ratio"].apply(compute_cohens_d)
    default_data = default_data[[
        "Outcome",
        "Risk, Odds, or Hazard Ratio",
        "Effect Size (Cohen's d, approx.)",
        "Lower CI",
        "Upper CI",
    ]]
    if "manual_table" not in st.session_state:
        st.session_state.manual_table = default_data.copy()

    _, col2 = st.columns([2, 1])
    with col2:
        if st.button("🧹 Clear Table"):
            st.session_state.manual_table = pd.DataFrame({col: [None] * 6 for col in required_cols})

    manual_df = st.session_state.manual_table.copy()
    manual_df["Effect Size (Cohen's d, approx.)"] = manual_df["Risk, Odds, or Hazard Ratio"].apply(compute_cohens_d)
    manual_df = manual_df[required_cols]
    st.session_state.manual_table = st.data_editor(
        manual_df,
        num_rows="dynamic",
        use_container_width=True,
        key="manual_input_table",
        column_config={
            "Effect Size (Cohen's d, approx.)": st.column_config.NumberColumn(
                "Effect Size (Cohen's d, approx.)",
                disabled=True,
                help="Auto-calculated as ln(RR/OR/HR) × sqrt(3)/π",
            )
        },
    )
    df = st.session_state.manual_table

if df is not None:
    st.sidebar.header("⚙️ Basic Plot Settings")

    x_measure = st.sidebar.radio(
        "Plot on X-axis",
        ("Effect Size (Cohen's d, approx.)", "Risk, Odds, or Hazard Ratio"),
        index=1,
    )

    plot_title = st.sidebar.text_input("Plot Title", value="Forest Plot")
    show_grid = st.sidebar.checkbox("Show Grid", value=True)
    show_values = st.sidebar.checkbox("Show Numerical Annotations", value=False)
    use_groups = st.sidebar.checkbox("Treat rows starting with '##' as section headers", value=True)

    with st.sidebar.expander("🎨 Advanced Visual Controls", expanded=False):
        color_scheme = st.selectbox("Color Scheme", ["Color", "Black & White"])
        point_size = st.slider("Marker Size", 6, 20, 10)
        line_width = st.slider("CI Line Width", 1, 4, 2)
        font_size = st.slider("Font Size", 10, 20, 12)
        label_offset = st.slider("Label Horizontal Offset", 0.01, 0.3, 0.05)
        use_log = st.checkbox("Use Log Scale for X-axis", value=False)
        axis_padding = st.slider("X-axis Padding (%)", 2, 40, 10)
        y_axis_padding = st.slider("Y-axis Padding (Rows)", 0.0, 5.0, 1.0, step=0.5)
        cap_height = st.slider("Tick Height (for CI ends)", 0.05, 0.5, 0.18, step=0.01)
        if color_scheme == "Color":
            ci_color = st.color_picker("CI Color", "#1f77b4")
            marker_color = st.color_picker("Point Color", "#d62728")
        else:
            ci_color = "black"
            marker_color = "black"

    if x_measure == "Effect Size (Cohen's d, approx.)":
        plot_column = "Effect Size (Cohen's d, approx.)"
        ci_l = df["Lower CI"].apply(compute_cohens_d)
        ci_u = df["Upper CI"].apply(compute_cohens_d)
        ci_vals = pd.concat([ci_l.dropna(), ci_u.dropna(), df[plot_column].dropna()])
        ref_line = 0
    else:
        plot_column = "Risk, Odds, or Hazard Ratio"
        ci_l = pd.to_numeric(df["Lower CI"], errors="coerce")
        ci_u = pd.to_numeric(df["Upper CI"], errors="coerce")
        ci_vals = pd.concat([ci_l.dropna(), ci_u.dropna(), pd.to_numeric(df[plot_column], errors="coerce").dropna()])
        ref_line = 1

    x_axis_label = plot_column

    if st.button("📊 Generate Forest Plot"):
        rows = []
        y_labels = []
        text_styles = []
        indent = "\u00A0" * 4
        group_mode = False

        for _, row in df.iterrows():
            if use_groups and isinstance(row["Outcome"], str) and row["Outcome"].startswith("##"):
                header = row["Outcome"][3:].strip()
                y_labels.append(header)
                text_styles.append("bold")
                rows.append(None)
                group_mode = True
            else:
                display_name = f"{indent}{row['Outcome']}" if group_mode else row["Outcome"]
                y_labels.append(display_name)
                text_styles.append("normal")
                rows.append(row)

        if ci_vals.empty:
            st.error("No plottable effect estimates were found.")
        else:
            fig, ax = plt.subplots(figsize=(10, max(2.5, len(y_labels) * 0.7)))
            x_min, x_max = ci_vals.min(), ci_vals.max()
            x_pad = (x_max - x_min) * (axis_padding / 100) if x_max != x_min else 0.1
            ax.set_xlim(x_min - x_pad, x_max + x_pad)

            for i, row in enumerate(rows):
                if row is None:
                    continue

                if x_measure == "Effect Size (Cohen's d, approx.)":
                    effect = row.get("Effect Size (Cohen's d, approx.)", np.nan)
                    lci = compute_cohens_d(row.get("Lower CI", np.nan))
                    uci = compute_cohens_d(row.get("Upper CI", np.nan))
                else:
                    effect = pd.to_numeric(pd.Series([row.get("Risk, Odds, or Hazard Ratio", np.nan)]), errors="coerce").iloc[0]
                    lci = pd.to_numeric(pd.Series([row.get("Lower CI", np.nan)]), errors="coerce").iloc[0]
                    uci = pd.to_numeric(pd.Series([row.get("Upper CI", np.nan)]), errors="coerce").iloc[0]

                if pd.notnull(lci) and pd.notnull(uci):
                    ax.hlines(i, xmin=lci, xmax=uci, color=ci_color, linewidth=line_width, capstyle="round")
                    ax.vlines(
                        [lci, uci],
                        [i - cap_height, i - cap_height],
                        [i + cap_height, i + cap_height],
                        color=ci_color,
                        linewidth=line_width,
                    )

                if pd.notnull(effect):
                    ax.plot(effect, i, "o", color=marker_color, markersize=point_size, zorder=3)
                    if show_values and pd.notnull(lci) and pd.notnull(uci):
                        label = f"{effect:.2f} [{lci:.2f}, {uci:.2f}]"
                        ax.text(uci + label_offset, i, label, va="center", fontsize=font_size - 2)

            ax.axvline(x=ref_line, color="gray", linestyle="--", linewidth=1)
            ax.set_yticks(range(len(y_labels)))
            for tick_label, style in zip(ax.set_yticklabels(y_labels), text_styles):
                if style == "bold":
                    tick_label.set_fontweight("bold")
                tick_label.set_fontsize(font_size)

            if use_log:
                try:
                    ax.set_xscale("log")
                except Exception:
                    st.warning("Log scale is only valid for positive numbers.")
            if show_grid:
                ax.grid(True, axis="x", linestyle=":", linewidth=0.6)
            else:
                ax.grid(False)

            ax.set_ylim(len(y_labels) - 1 + y_axis_padding, -1 - y_axis_padding)
            ax.set_xlabel(x_axis_label, fontsize=font_size)
            ax.set_title(plot_title, fontsize=font_size + 2, weight="bold")
            fig.tight_layout()
            st.pyplot(fig)

            buf = io.BytesIO()
            fig.savefig(buf, format="png", dpi=300, bbox_inches="tight")
            st.download_button(
                "📥 Download Plot as PNG",
                data=buf.getvalue(),
                file_name="forest_plot.png",
                mime="image/png",
            )
else:
    st.info("Please upload file(s) or enter data manually to generate a plot.")
