import csv
import io
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st

plt.style.use("seaborn-v0_8-whitegrid")
st.set_page_config(layout="wide")
st.title("🌲 Novak's TriNetX Forest Plot Generator")

required_cols = [
    "Outcome",
    "Risk, Odds, or Hazard Ratio",
    "Effect Size (Cohen's d, approx.)",
    "Lower CI",
    "Upper CI",
]


# =========================
# Core utilities
# =========================
def compute_cohens_d(rr):
    try:
        if pd.isnull(rr):
            return np.nan
        val = float(rr)
        if val <= 0:
            return np.nan
        return np.log(val) * (np.sqrt(3) / np.pi)
    except Exception:
        return np.nan


def clean_cell(value):
    if value is None:
        return ""
    text = str(value).replace("\ufeff", "").strip()
    text = text.strip('"').strip()
    return text


def parse_float(value):
    text = clean_cell(value).replace(",", "")
    if text in {"", " ", "nan", "None"}:
        return None
    try:
        return float(text)
    except Exception:
        return None


def next_nonblank_row(rows, start_idx):
    for idx in range(start_idx, len(rows)):
        if any(clean_cell(cell) for cell in rows[idx]):
            return idx
    return None


# =========================
# TriNetX parsing helpers
# =========================
def extract_section_triplet(rows, section_name):
    for i, row in enumerate(rows):
        first = clean_cell(next((cell for cell in row if clean_cell(cell)), ""))
        if first == section_name:
            header_idx = next_nonblank_row(rows, i + 1)
            data_idx = next_nonblank_row(rows, (header_idx + 1) if header_idx is not None else i + 1)
            if data_idx is None:
                return None
            numeric_values = [parse_float(cell) for cell in rows[data_idx]]
            numeric_values = [x for x in numeric_values if x is not None]
            if len(numeric_values) >= 3:
                return {
                    "estimate": numeric_values[0],
                    "lower": numeric_values[1],
                    "upper": numeric_values[2],
                }
    return None


def extract_section_value_map(rows, section_name):
    for i, row in enumerate(rows):
        first = clean_cell(next((cell for cell in row if clean_cell(cell)), ""))
        if first == section_name:
            header_idx = next_nonblank_row(rows, i + 1)
            data_idx = next_nonblank_row(rows, (header_idx + 1) if header_idx is not None else i + 1)
            if header_idx is None or data_idx is None:
                return None
            headers = [clean_cell(x) for x in rows[header_idx]]
            values = [clean_cell(x) for x in rows[data_idx]]
            out = {}
            for h, v in zip(headers, values):
                if h:
                    out[h] = v
            return out
    return None


def extract_title_from_rows(rows):
    for row in rows[:8]:
        first = clean_cell(next((cell for cell in row if clean_cell(cell)), ""))
        if first and first != "Generated by TriNetX":
            return first
    return ""


def detect_trinetx_table_type(title, raw_text):
    title_clean = clean_cell(title)
    raw_text = raw_text or ""
    if "Kaplan-Meier Table" in title_clean or "Kaplan-Meier Table" in raw_text:
        return "Kaplan-Meier"
    if "Measures of Association Table" in title_clean or "Measures of Association Table" in raw_text:
        return "Measures of Association"
    if "Hazard Ratio" in raw_text and "Log-Rank Test" in raw_text:
        return "Kaplan-Meier"
    if any(x in raw_text for x in ["Risk Ratio", "Odds Ratio"]):
        return "Measures of Association"
    return "TriNetX"


def clean_title(title):
    title = clean_cell(title)
    title = re.sub(r"\s*Measures of Association Table\s*$", "", title, flags=re.IGNORECASE)
    title = re.sub(r"\s*Kaplan[- ]Meier Table\s*$", "", title, flags=re.IGNORECASE)
    title = re.sub(r"\s+", " ", title).strip(" -_")
    return title


def clean_filename(name):
    stem = Path(name).stem
    stem = re.sub(r"(?i)_result_[a-z0-9]+_moa_table$", "", stem)
    stem = re.sub(r"(?i)_result_[a-z0-9]+_km_table$", "", stem)
    stem = re.sub(r"(?i)_moa_table$", "", stem)
    stem = re.sub(r"(?i)_km_table$", "", stem)
    stem = re.sub(r"(?i)_kaplan[-_ ]meier_table$", "", stem)
    stem = re.sub(r"(?i)_table$", "", stem)
    stem = stem.replace("_", " ").replace("-", " ")
    stem = re.sub(r"\s+", " ", stem).strip()
    return stem


def looks_generic(label):
    text = (label or "").strip().lower()
    return bool(re.match(r"^outcome\s*\d+(\s+result.*)?$", text))


def choose_outcome_label(title, filename):
    cleaned_title = clean_title(title)
    cleaned_filename = clean_filename(filename)
    if cleaned_title and not looks_generic(cleaned_title):
        return cleaned_title
    if cleaned_filename:
        return cleaned_filename
    return cleaned_title or "Outcome"


def parse_trinetx_csv_text(file_bytes):
    text = file_bytes.decode("utf-8-sig", errors="ignore")
    rows = list(csv.reader(io.StringIO(text)))
    return rows, text


def parse_trinetx_excel_rows(file_bytes):
    raw = pd.read_excel(io.BytesIO(file_bytes), header=None, dtype=str)
    rows = raw.fillna("").values.tolist()
    joined = "\n".join([",".join([clean_cell(cell) for cell in row]) for row in rows])
    return rows, joined


def parse_trinetx_effect_rows(rows, filename, raw_text):
    title = extract_title_from_rows(rows)
    table_type = detect_trinetx_table_type(title, raw_text)

    risk_ratio = extract_section_triplet(rows, "Risk Ratio")
    odds_ratio = extract_section_triplet(rows, "Odds Ratio")
    hazard_ratio = extract_section_triplet(rows, "Hazard Ratio")

    if not any([risk_ratio, odds_ratio, hazard_ratio]):
        return None

    log_rank = extract_section_value_map(rows, "Log-Rank Test") if table_type == "Kaplan-Meier" else None
    proportionality = extract_section_value_map(rows, "Proportionality") if table_type == "Kaplan-Meier" else None

    return {
        "Outcome": choose_outcome_label(title, filename),
        "Original Title": clean_title(title),
        "Source File": filename,
        "TriNetX Table Type": table_type,
        "Risk Ratio": risk_ratio["estimate"] if risk_ratio else np.nan,
        "RR Lower CI": risk_ratio["lower"] if risk_ratio else np.nan,
        "RR Upper CI": risk_ratio["upper"] if risk_ratio else np.nan,
        "Odds Ratio": odds_ratio["estimate"] if odds_ratio else np.nan,
        "OR Lower CI": odds_ratio["lower"] if odds_ratio else np.nan,
        "OR Upper CI": odds_ratio["upper"] if odds_ratio else np.nan,
        "Hazard Ratio": hazard_ratio["estimate"] if hazard_ratio else np.nan,
        "HR Lower CI": hazard_ratio["lower"] if hazard_ratio else np.nan,
        "HR Upper CI": hazard_ratio["upper"] if hazard_ratio else np.nan,
        "Log-Rank p": parse_float(log_rank.get("p")) if log_rank else np.nan,
        "PH Assumption p": parse_float(proportionality.get("p")) if proportionality else np.nan,
    }


# =========================
# Standard table handling
# =========================
def standardize_existing_forest_table(df):
    working = df.copy()
    for col in required_cols:
        if col not in working.columns:
            working[col] = np.nan

    numeric_cols = [
        "Risk, Odds, or Hazard Ratio",
        "Lower CI",
        "Upper CI",
        "Effect Size (Cohen's d, approx.)",
    ]
    for col in numeric_cols:
        working[col] = pd.to_numeric(working[col], errors="coerce")

    if working["Effect Size (Cohen's d, approx.)"].isna().all():
        working["Effect Size (Cohen's d, approx.)"] = working["Risk, Odds, or Hazard Ratio"].apply(compute_cohens_d)

    return working[required_cols]


# =========================
# Upload detection
# =========================
def looks_like_trinetx_text(raw_text):
    if not raw_text:
        return False
    return "Generated by TriNetX" in raw_text and any(
        x in raw_text for x in ["Risk Ratio", "Odds Ratio", "Hazard Ratio", "Kaplan-Meier Table", "Measures of Association Table"]
    )


def detect_and_load_uploaded_files(uploaded_files):
    parsed_trinetx_rows = []
    parsed_standard_tables = []
    parsing_notes = []

    for uploaded_file in uploaded_files:
        file_bytes = uploaded_file.getvalue()
        filename = uploaded_file.name
        suffix = Path(filename).suffix.lower()

        try:
            if suffix == ".csv":
                rows, raw_text = parse_trinetx_csv_text(file_bytes)
                if looks_like_trinetx_text(raw_text):
                    parsed = parse_trinetx_effect_rows(rows, filename, raw_text)
                    if parsed is not None:
                        parsed_trinetx_rows.append(parsed)
                        continue
                standard_df = pd.read_csv(io.BytesIO(file_bytes))
                parsed_standard_tables.append(standardize_existing_forest_table(standard_df))

            elif suffix in {".xlsx", ".xls"}:
                try:
                    rows, raw_text = parse_trinetx_excel_rows(file_bytes)
                    if looks_like_trinetx_text(raw_text):
                        parsed = parse_trinetx_effect_rows(rows, filename, raw_text)
                        if parsed is not None:
                            parsed_trinetx_rows.append(parsed)
                            continue
                except Exception:
                    pass
                standard_df = pd.read_excel(io.BytesIO(file_bytes))
                parsed_standard_tables.append(standardize_existing_forest_table(standard_df))

            else:
                parsing_notes.append(f"Skipped unsupported file type: {filename}")
        except Exception as e:
            parsing_notes.append(f"Could not parse {filename}: {e}")

    return parsed_trinetx_rows, parsed_standard_tables, parsing_notes


# =========================
# Forest plot table assembly
# =========================
def choose_effect_for_row(row, preferred_measure):
    measure_priority = [preferred_measure]
    for candidate in ["Risk Ratio", "Odds Ratio", "Hazard Ratio"]:
        if candidate not in measure_priority:
            measure_priority.append(candidate)

    for candidate in measure_priority:
        if candidate == "Risk Ratio" and pd.notnull(row.get("Risk Ratio", np.nan)):
            return candidate, row["Risk Ratio"], row["RR Lower CI"], row["RR Upper CI"]
        if candidate == "Odds Ratio" and pd.notnull(row.get("Odds Ratio", np.nan)):
            return candidate, row["Odds Ratio"], row["OR Lower CI"], row["OR Upper CI"]
        if candidate == "Hazard Ratio" and pd.notnull(row.get("Hazard Ratio", np.nan)):
            return candidate, row["Hazard Ratio"], row["HR Lower CI"], row["HR Upper CI"]

    return None, np.nan, np.nan, np.nan


def deduplicate_outcome_labels(df):
    df = df.copy()
    counts = df["Outcome"].value_counts(dropna=False)
    duplicate_labels = set(counts[counts > 1].index.tolist())

    def relabel(row):
        label = row["Outcome"]
        if label in duplicate_labels:
            effect_type = row.get("Effect Type")
            table_type = row.get("TriNetX Table Type")
            if pd.notnull(effect_type) and pd.notnull(table_type):
                return f"{label} — {effect_type} ({table_type})"
            if pd.notnull(effect_type):
                return f"{label} — {effect_type}"
        return label

    df["Outcome"] = df.apply(relabel, axis=1)
    return df


def build_plot_table_from_trinetx(parsed_rows, preferred_measure):
    out_rows = []

    for row in parsed_rows:
        chosen_measure, estimate, lower, upper = choose_effect_for_row(row, preferred_measure)
        out_rows.append({
            "Outcome": row["Outcome"],
            "Risk, Odds, or Hazard Ratio": estimate,
            "Effect Size (Cohen's d, approx.)": compute_cohens_d(estimate),
            "Lower CI": lower,
            "Upper CI": upper,
            "Effect Type": chosen_measure,
            "TriNetX Table Type": row["TriNetX Table Type"],
            "Log-Rank p": row.get("Log-Rank p", np.nan),
            "PH Assumption p": row.get("PH Assumption p", np.nan),
            "Source File": row["Source File"],
        })

    built = pd.DataFrame(out_rows)
    if not built.empty:
        built = deduplicate_outcome_labels(built)
    return built


def infer_ratio_axis_label(df):
    if "Effect Type" in df.columns:
        effect_types = [str(x).strip() for x in df["Effect Type"].dropna().tolist() if str(x).strip()]
        unique_effect_types = list(dict.fromkeys(effect_types))
        if len(unique_effect_types) == 1:
            return unique_effect_types[0]
        if len(unique_effect_types) > 1:
            return "Effect Estimate"
    return st.session_state.get("manual_ratio_label", "Risk Ratio")


def compute_ratio_axis_limits(ci_vals, axis_padding, use_log=False):
    numeric_vals = pd.to_numeric(ci_vals, errors="coerce")
    numeric_vals = numeric_vals.replace([np.inf, -np.inf], np.nan).dropna()
    numeric_vals = numeric_vals[numeric_vals > 0]

    if numeric_vals.empty:
        return 0.5, 1.5

    raw_min = float(min(numeric_vals.min(), 1.0))
    raw_max = float(max(numeric_vals.max(), 1.0))

    if use_log:
        lower_factor = 1.0 / raw_min if raw_min > 0 else raw_max
        upper_factor = raw_max
        factor = max(lower_factor, upper_factor, 1.25)
        factor *= (1 + axis_padding / 100)
        return max(1 / factor, 1e-6), factor

    dist_left = max(1.0 - raw_min, 0.0)
    dist_right = max(raw_max - 1.0, 0.0)
    half_span = max(dist_left, dist_right)
    if half_span == 0:
        half_span = 0.25
    padded_half_span = half_span * (1 + axis_padding / 100)
    auto_min = max(0.0, 1.0 - padded_half_span)
    auto_max = 1.0 + padded_half_span
    if auto_min == auto_max:
        auto_max = auto_min + 1.0
    return auto_min, auto_max


# =========================
# App UI
# =========================
input_mode = st.radio(
    "Select data input method:", ["📤 Upload file(s)", "✍️ Manual entry"], index=0, horizontal=True
)

df = None

if input_mode == "📤 Upload file(s)":
    uploaded_files = st.file_uploader(
        "Upload one normalized forest-plot table or multiple raw TriNetX MOA / Kaplan–Meier summary tables",
        type=["csv", "xlsx", "xls"],
        accept_multiple_files=True,
    )

    if uploaded_files:
        preferred_measure = st.sidebar.selectbox(
            "Preferred TriNetX estimate to plot",
            ["Risk Ratio", "Odds Ratio", "Hazard Ratio"],
            index=0,
            help="For MOA files, the app will prefer this estimate when available. KM tables contribute Hazard Ratios automatically.",
        )
        st.session_state["manual_ratio_label"] = preferred_measure

        parsed_trinetx_rows, parsed_standard_tables, parsing_notes = detect_and_load_uploaded_files(uploaded_files)

        assembled_tables = []
        if parsed_trinetx_rows:
            trinetx_df = build_plot_table_from_trinetx(parsed_trinetx_rows, preferred_measure)
            assembled_tables.append(
                trinetx_df[required_cols + ["Effect Type", "TriNetX Table Type", "Log-Rank p", "PH Assumption p", "Source File"]]
            )
        if parsed_standard_tables:
            for table in parsed_standard_tables:
                table = table.copy()
                table["Effect Type"] = np.nan
                table["TriNetX Table Type"] = np.nan
                table["Log-Rank p"] = np.nan
                table["PH Assumption p"] = np.nan
                table["Source File"] = np.nan
                assembled_tables.append(
                    table[required_cols + ["Effect Type", "TriNetX Table Type", "Log-Rank p", "PH Assumption p", "Source File"]]
                )

        if assembled_tables:
            combined_df = pd.concat(assembled_tables, ignore_index=True)
            st.subheader("Parsed data preview")
            st.caption(
                "You can edit outcome labels, reorder rows, or insert section headers using ## before a label. "
                "KM uploads populate hazard ratios and preserve log-rank / proportionality p-values as metadata."
            )
            editable_cols = required_cols + ["Effect Type", "TriNetX Table Type", "Log-Rank p", "PH Assumption p", "Source File"]
            edited_df = st.data_editor(
                combined_df[editable_cols],
                num_rows="dynamic",
                use_container_width=True,
                key="uploaded_table_editor",
                column_config={
                    "Effect Size (Cohen's d, approx.)": st.column_config.NumberColumn(
                        "Effect Size (Cohen's d, approx.)",
                        disabled=True,
                        help="Auto-calculated as ln(RR/OR/HR) × sqrt(3)/π",
                    ),
                    "Effect Type": st.column_config.TextColumn(disabled=True),
                    "TriNetX Table Type": st.column_config.TextColumn(disabled=True),
                    "Log-Rank p": st.column_config.NumberColumn(disabled=True, format="%.4g"),
                    "PH Assumption p": st.column_config.NumberColumn(disabled=True, format="%.4g"),
                    "Source File": st.column_config.TextColumn(disabled=True),
                },
            )
            edited_df["Effect Size (Cohen's d, approx.)"] = edited_df["Risk, Odds, or Hazard Ratio"].apply(compute_cohens_d)
            df = edited_df

            summary_bits = []
            if parsed_trinetx_rows:
                n_km = sum(1 for r in parsed_trinetx_rows if r.get("TriNetX Table Type") == "Kaplan-Meier")
                n_moa = sum(1 for r in parsed_trinetx_rows if r.get("TriNetX Table Type") == "Measures of Association")
                if n_moa:
                    summary_bits.append(f"{n_moa} MOA file(s)")
                if n_km:
                    summary_bits.append(f"{n_km} KM file(s)")
            if parsed_standard_tables:
                summary_bits.append(f"{len(parsed_standard_tables)} preformatted table(s)")
            if summary_bits:
                st.success("Parsed: " + ", ".join(summary_bits))
        else:
            st.error("No usable forest-plot data could be parsed from the uploaded files.")

        if parsing_notes:
            with st.expander("Parsing notes"):
                for note in parsing_notes:
                    st.write(f"- {note}")
else:
    default_data = pd.DataFrame({
        "Outcome": ["## Cardiovascular", "Hypertension", "Stroke", "## Metabolic", "Diabetes", "Obesity"],
        "Risk, Odds, or Hazard Ratio": [None, 1.5, 1.2, None, 0.85, 1.2],
        "Lower CI": [None, 1.2, 1.0, None, 0.7, 1.0],
        "Upper CI": [None, 1.8, 1.5, None, 1.0, 1.4],
    })
    default_data["Effect Size (Cohen's d, approx.)"] = default_data["Risk, Odds, or Hazard Ratio"].apply(compute_cohens_d)
    default_data = default_data[required_cols]

    if "manual_table" not in st.session_state:
        st.session_state.manual_table = default_data.copy()

    _, col2 = st.columns([2, 1])
    with col2:
        if st.button("🧹 Clear Table"):
            st.session_state.manual_table = pd.DataFrame({col: [None] * 6 for col in required_cols})

    manual_df = st.session_state.manual_table.copy()
    manual_df["Effect Size (Cohen's d, approx.)"] = manual_df["Risk, Odds, or Hazard Ratio"].apply(compute_cohens_d)
    manual_df = manual_df[required_cols]
    st.session_state.manual_table = st.data_editor(
        manual_df,
        num_rows="dynamic",
        use_container_width=True,
        key="manual_input_table",
        column_config={
            "Effect Size (Cohen's d, approx.)": st.column_config.NumberColumn(
                "Effect Size (Cohen's d, approx.)",
                disabled=True,
                help="Auto-calculated as ln(RR/OR/HR) × sqrt(3)/π",
            )
        },
    )
    df = st.session_state.manual_table


# =========================
# Plotting
# =========================
if df is not None:
    st.sidebar.header("⚙️ Basic Plot Settings")

    x_measure = st.sidebar.radio(
        "Plot on X-axis",
        ("Effect Size (Cohen's d, approx.)", "Risk, Odds, or Hazard Ratio"),
        index=1,
    )

    if x_measure == "Risk, Odds, or Hazard Ratio" and "Effect Type" not in df.columns:
        default_ratio_label_index = ["Risk Ratio", "Odds Ratio", "Hazard Ratio"].index(
            st.session_state.get("manual_ratio_label", "Risk Ratio")
        ) if st.session_state.get("manual_ratio_label", "Risk Ratio") in ["Risk Ratio", "Odds Ratio", "Hazard Ratio"] else 0
        st.session_state["manual_ratio_label"] = st.sidebar.selectbox(
            "Label ratio axis as",
            ["Risk Ratio", "Odds Ratio", "Hazard Ratio"],
            index=default_ratio_label_index,
            help="Use this when the uploaded table does not include an explicit effect type column.",
        )

    plot_title = st.sidebar.text_input("Plot Title", value="Forest Plot")
    show_grid = st.sidebar.checkbox("Show Grid", value=True)
    show_values = st.sidebar.checkbox("Show Numerical Annotations", value=False)
    use_groups = st.sidebar.checkbox("Treat rows starting with '##' as section headers", value=True)

    with st.sidebar.expander("🎨 Advanced Visual Controls", expanded=False):
        color_scheme = st.selectbox("Color Scheme", ["Color", "Black & White"])
        point_size = st.slider("Marker Size", 6, 20, 10)
        line_width = st.slider("CI Line Width", 1, 4, 2)
        font_size = st.slider("Font Size", 10, 20, 12)
        label_offset = st.slider("Label Horizontal Offset", 0.01, 0.3, 0.05)
        use_log = st.checkbox("Use Log Scale for X-axis", value=False)
        axis_padding = st.slider("X-axis Padding (%)", 2, 40, 10)
        manual_x_axis = st.checkbox(
            "Specify X-axis range manually",
            value=False,
            help="Turn this on to set the plotted X-axis minimum and maximum yourself instead of using automatic padding.",
        )
        y_axis_padding = st.slider("Y-axis Padding (Rows)", 0.0, 5.0, 1.0, step=0.5)
        cap_height = st.slider("Tick Height (for CI ends)", 0.05, 0.5, 0.18, step=0.01)
        if color_scheme == "Color":
            ci_color = st.color_picker("CI Color", "#1f77b4")
            marker_color = st.color_picker("Point Color", "#d62728")
        else:
            ci_color = "black"
            marker_color = "black"

    if x_measure == "Effect Size (Cohen's d, approx.)":
        plot_column = "Effect Size (Cohen's d, approx.)"
        ci_l = df["Lower CI"].apply(compute_cohens_d)
        ci_u = df["Upper CI"].apply(compute_cohens_d)
        ci_vals = pd.concat([ci_l.dropna(), ci_u.dropna(), df[plot_column].dropna()])
        ref_line = 0
    else:
        plot_column = "Risk, Odds, or Hazard Ratio"
        ci_l = pd.to_numeric(df["Lower CI"], errors="coerce")
        ci_u = pd.to_numeric(df["Upper CI"], errors="coerce")
        ci_vals = pd.concat([ci_l.dropna(), ci_u.dropna(), pd.to_numeric(df[plot_column], errors="coerce").dropna()])
        ref_line = 1

    if x_measure == "Risk, Odds, or Hazard Ratio":
        x_axis_label = infer_ratio_axis_label(df)
        auto_x_min, auto_x_max = compute_ratio_axis_limits(ci_vals, axis_padding, use_log=use_log)
    else:
        x_axis_label = plot_column
        auto_x_min = ci_vals.min() if not ci_vals.empty else None
        auto_x_max = ci_vals.max() if not ci_vals.empty else None

    auto_x_span = (auto_x_max - auto_x_min) if auto_x_min is not None and auto_x_max is not None else None
    default_x_pad = (auto_x_span * (axis_padding / 100)) if auto_x_span is not None and auto_x_span != 0 else 0.1

    if manual_x_axis:
        x_input_help = "Set the minimum and maximum X-axis values to control the full plotted range."
        if auto_x_min is None or auto_x_max is None:
            manual_x_min = st.sidebar.number_input("X-axis minimum", value=0.0, format="%.4f", help=x_input_help)
            manual_x_max = st.sidebar.number_input("X-axis maximum", value=2.0, format="%.4f", help=x_input_help)
        else:
            manual_x_min = st.sidebar.number_input(
                "X-axis minimum",
                value=float(auto_x_min - default_x_pad),
                format="%.4f",
                help=x_input_help,
            )
            manual_x_max = st.sidebar.number_input(
                "X-axis maximum",
                value=float(auto_x_max + default_x_pad),
                format="%.4f",
                help=x_input_help,
            )
    else:
        manual_x_min = None
        manual_x_max = None

    if st.button("📊 Generate Forest Plot"):
        rows = []
        y_labels = []
        text_styles = []
        indent = "\u00A0" * 4
        group_mode = False

        for _, row in df.iterrows():
            if use_groups and isinstance(row["Outcome"], str) and row["Outcome"].startswith("##"):
                header = row["Outcome"][3:].strip()
                y_labels.append(header)
                text_styles.append("bold")
                rows.append(None)
                group_mode = True
            else:
                display_name = f"{indent}{row['Outcome']}" if group_mode else row["Outcome"]
                y_labels.append(display_name)
                text_styles.append("normal")
                rows.append(row)

        if ci_vals.empty:
            st.error("No plottable effect estimates were found.")
        else:
            fig, ax = plt.subplots(figsize=(10, max(2.5, len(y_labels) * 0.7)))

            if manual_x_axis:
                if manual_x_min >= manual_x_max:
                    st.error("The X-axis minimum must be smaller than the X-axis maximum.")
                    st.stop()
                ax.set_xlim(manual_x_min, manual_x_max)
            else:
                if x_measure == "Risk, Odds, or Hazard Ratio":
                    auto_plot_x_min, auto_plot_x_max = compute_ratio_axis_limits(ci_vals, axis_padding, use_log=use_log)
                    ax.set_xlim(auto_plot_x_min, auto_plot_x_max)
                else:
                    x_min, x_max = ci_vals.min(), ci_vals.max()
                    x_pad = (x_max - x_min) * (axis_padding / 100) if x_max != x_min else 0.1
                    ax.set_xlim(x_min - x_pad, x_max + x_pad)

            for i, row in enumerate(rows):
                if row is None:
                    continue

                if x_measure == "Effect Size (Cohen's d, approx.)":
                    effect = row.get("Effect Size (Cohen's d, approx.)", np.nan)
                    lci = compute_cohens_d(row.get("Lower CI", np.nan))
                    uci = compute_cohens_d(row.get("Upper CI", np.nan))
                else:
                    effect = pd.to_numeric(pd.Series([row.get("Risk, Odds, or Hazard Ratio", np.nan)]), errors="coerce").iloc[0]
                    lci = pd.to_numeric(pd.Series([row.get("Lower CI", np.nan)]), errors="coerce").iloc[0]
                    uci = pd.to_numeric(pd.Series([row.get("Upper CI", np.nan)]), errors="coerce").iloc[0]

                if pd.notnull(lci) and pd.notnull(uci):
                    ax.hlines(i, xmin=lci, xmax=uci, color=ci_color, linewidth=line_width, capstyle="round")
                    ax.vlines(
                        [lci, uci],
                        [i - cap_height, i - cap_height],
                        [i + cap_height, i + cap_height],
                        color=ci_color,
                        linewidth=line_width,
                    )

                if pd.notnull(effect):
                    ax.plot(effect, i, "o", color=marker_color, markersize=point_size, zorder=3)
                    if show_values and pd.notnull(lci) and pd.notnull(uci):
                        label = f"{effect:.2f} [{lci:.2f}, {uci:.2f}]"
                        ax.text(uci + label_offset, i, label, va="center", fontsize=font_size - 2)

            ax.axvline(x=ref_line, color="gray", linestyle="--", linewidth=1)
            ax.set_yticks(range(len(y_labels)))
            for tick_label, style in zip(ax.set_yticklabels(y_labels), text_styles):
                if style == "bold":
                    tick_label.set_fontweight("bold")
                tick_label.set_fontsize(font_size)

            if use_log:
                try:
                    ax.set_xscale("log")
                except Exception:
                    st.warning("Log scale is only valid for positive numbers.")
            if show_grid:
                ax.grid(True, axis="x", linestyle=":", linewidth=0.6)
            else:
                ax.grid(False)

            ax.set_ylim(len(y_labels) - 1 + y_axis_padding, -1 - y_axis_padding)
            ax.set_xlabel(x_axis_label, fontsize=font_size)
            ax.set_title(plot_title, fontsize=font_size + 2, weight="bold")
            fig.tight_layout()
            st.pyplot(fig)

            buf = io.BytesIO()
            fig.savefig(buf, format="png", dpi=300, bbox_inches="tight")
            st.download_button(
                "📥 Download Plot as PNG",
                data=buf.getvalue(),
                file_name="forest_plot.png",
                mime="image/png",
            )
else:
    st.info("Please upload file(s) or enter data manually to generate a plot.")
